### ISSUE TITLE
print bug

### ISSUE THREAD

**Issue by hananabilabd** [ece-mohammad/RegMask#1]
hello mohsen when i run main.py 
![image](https://user-images.githubusercontent.com/26032494/54790809-28f0d300-4c40-11e9-98a2-a896876b3592.png)

**Comment by ece-mohammad** [comment]
This issue happens when running `main.py` using python 2.

Due to the usage of print in `OctetFrame` in the code below `__main__`, the interpreter flags this as a syntax error. That code was used for checking that each part was working correctly, so it's not important to run the program. So, i just commented that out for now. So, this bug should be resolved.

I'll try adding compatibility with python 2 as well in the upcoming version.
